### ISSUE TITLE
Rename higher & lower

### ISSUE THREAD

**Issue by lukasoppermann** [lookitsatravis/listify#18]
How about renaming (or aliasing) higher and lower to up and down. Since in the readme you already mention it is confusing. 😄

**Comment by stevendesu** [comment]
Not the library author, but I would definitely recommend aliasing instead of renaming. I like the "higher" and "lower" naming schema because it maps directly to a data table view. If you want to move something "lower" in a list then it needs to come "after" the other items, meaning it needs a higher value for "position"

Of course then there's the challenge of explaining to people why you have a `moveHigher` function and a `moveUp` function and what the difference is between the two 😄

**Comment by lookitsatravis** [comment]
Closing all issues due to inactivity of this project. The repository will be archived shortly. Thanks for understanding.
