### ISSUE TITLE
Broken in Laravel 5.4.36 ?

### ISSUE THREAD

**Issue by eminos** [lookitsatravis/listify#24]
This package seems to be broken in Laravel 5.4.36. It worked fine with "5.4 from this spring".

Instead of updating the position column it creates a new item row altogether.

**Comment by lookitsatravis** [comment]
@eminos would you be able to provide an example which is not working as expected? A repo would be ideal since there are a number of dependencies to getting the package to work in your project. 5.4.36 does not (or rather, should not) have any changes which impact Listify according to the change log.

Hopefully it's just a configuration thing we can work through. I am not going to provide any patches to the existing version, because I am working on v2 which should be released soon. So, if there truly is a failure, I will make sure v2 address it.

Thanks!

**Comment by eminos** [comment]
@lookitsatravis I'm so sorry. It was totally a bug on my end. This issue should be closed.
Thanks for an awesome package!

**Comment by lookitsatravis** [comment]
No worries! Thanks for the kind words. Take care!
